---
title: "Math expressions, functions, and modeling"
---

```{r setup, message=FALSE}
library(tidyverse)

theme_set(
	theme_classic() +
		theme(
			text = element_text(family = "mono", face = "bold", size = 14)
		)
)
```

# GETTING HELP

Getting help about objects in a package

```{rm eval=F}
# show documentation for pkg
library(help = "base")

# ls all objects in pkg and then search for a string
ls("package:base") %>% 
	grep(pattern = '\\[') %>%
	ls("package:base")[.]

# list currently loaded pkgs
search()

# open help page for pkg
help(package = "base")
```

# MODELING

## DATA

Use the iris dataset

```{r load-data}
# str(iris)
t_iris = as_tibble(iris)
```

## PLOT

```{r plot}
t_iris %>%
	ggplot(aes(x = Sepal.Length, y = Petal.Length)) + 
	geom_point() +
	geom_smooth(method = "lm")
```

## MODEL

```{r model}
# model petal length by sepal length
iris_mod_lin = lm(formula = Petal.Length ~ Sepal.Length, data = t_iris)
# summarize the model
iris_mod_lin_summ = summary(iris_mod_lin) ; iris_mod_lin_summ
```

Predict new values from model

```{r}
# predict values and add to table
t_iris$Petal.Length.pred = predict(iris_mod_lin)


```


```{r, eval=F}
rss_tab = estimate$measures$rss %>%
	as_tibble() %>%
	mutate(x = 1:nrow(.))

mod = lm(formula = value ~ I(1/x), data = rss_tab)
print(summary(mod))
pred = predict(object = mod)
print(cor(rss_tab$value, pred))

# make function
fun_pred = function(x) -92241 + 1386191*I(1/x)

# add predictions to table
rss_tab_pred = rss_tab %>%
	mutate(pred = pred)
rss_tab_pred

rss_tab_pred %>%
	ggplot(aes(x = x, y = value)) +
	geom_point() +
	# geom_line(aes(y = pred), color = "red")
	# stat_function(fun = fun_pred) +
	stat_smooth(method = "lm", formula = y ~ I(1/x), se = T)

# get derivative of best fit line
D(expr = expression(-92241 + 1386191*(1/x)), name = "x")
fun_deriv = function(x) eval(D(expr = expression(-92241 + 1386191*(1/x)), name = "x"))
uniroot(f = fun_deriv, interval = c(1, 10))
```


# math expressions, functions, and evaluations

relevant R functions - `call()` - `expression()` - `eval()` - `function()`

```{r}
exp = expression(x, 1 + 3*(1/x))
exp %>%
	class()
eval(expr = exp)
```

# `call()`, `do.call()`

```{r}
is.call(call) #-> FALSE: Functions are NOT calls

## set up a function call to round with argument 10.5
cl <- call("round", 10.5)
is.call(cl) # TRUE
cl
identical(quote(round(10.5)), # <- less functional, but the same
          cl) # TRUE
## such a call can also be evaluated.
eval(cl) # [1] 10

class(cl) # "call"
typeof(cl)# "language"
str(cl)
is.call(cl) && is.language(cl) # always TRUE for "call"s
A <- 10.5
call("round", A)        # round(10.5)
call("round", quote(A)) # round(A)
# ?quote
f <- "round"
call(f, quote(A))       # round(A)
## if we want to supply a function we need to use as.call or similar
f <- round
## Not run: call(f, quote(A))  # error: first arg must be character
(g <- as.call(list(f, quote(A))))
eval(g)
## alternatively but less transparently
g <- list(f, quote(A))
mode(g) <- "call"
g
eval(g)
## see also the examples in the help for do.call

```
